name: Connect to GCP to compute engine
on:
   push:
     branches:
       - main
jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Connect to GCP to compute engine
         run: |
           echo "$PEM_KEY" | base64 --decode > shahsahib28.pem
           chmod 400 shahsahib28.pem
           sudo su
           sudo apt-get -y install openssh-client
           ssh -v -o StrictHostKeyChecking=no -i shahsahib28.pem ec2-user@35.185.56.7 "cd /var/www/html/YPay-backend && git fetch origin && git reset --hard origin/ypayGCP && pm2 restart all"


























